export const Get_All_Category="Get_All_Category"
export const Get_Error=" Get_Error";
export const CREATE_CATEGORY="CREATE_CATEGORY"



export const Get_All_BRAND="Get_All_BRAND"
export const CREATE_BRAND="CREATE_BRAND"


export const CREATE_SUB_CATEGORY="CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY="GET_SUB_CATEGORY"
export const CREATE_PRODUCT="CREATE_PRODUCT"
export const GET_ALL_PRODUCT="GET_ALL_PRODUCT"
export const GET_PRODUCT_DETAILS="GET_PRODUCT_DETAILS"
export const GET_ONE_BRAND="GET_ONE_BRAND"
export const GET_ONE_CATEGORE="GET_ONE_CATEGORE"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const CREATE_USER="CREATE_USER"
export const LOGIN_USER="LOGIN_USER"
export const GET_CURRENT_USER="GET_CURRENT_USER"
export const FORGET_PASSWORD="FORGET_PASSWORD"
export const VERIFY_PASSWORD="VERIFY_PASSWORD"
export const RESET_PASSWORD="RESET_PASSWORD"